#!/bin/bash

if ! [ -z "$JOB_ID" ]
then
	echo "This script cannot be used via qsub"
	exit 1
fi

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

. $DIR/scripts/parse_args.sh

if ! [ -d "$OUT_DIR" ] || ! mkdir -p "$OUT_DIR"
then
	echo "Unable to make output directory"
	usage
fi
if ! [ -f "$RUN_DIR/SampleSheet.csv" ]
then
	echo "Run directory or sample sheet do not exist"
	usage
fi

echo $DIR/scripts/assemble_flowcell -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT" | \
	qsub -pe threaded 16 -l 'h_vmem=96G' -cwd -N assemble_flowcell -e $OUT_DIR/assemble_flowcell.err \
	-o $OUT_DIR/assemble_flowcell.out -m es -M $USER@illumina.com
