#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

. $DIR/scripts/parse_args.sh

if ! [ -d "$OUT_DIR" ] || ! mkdir -p "$OUT_DIR"
then
	echo "Unable to make output directory"
	usage
fi

if ! mkdir -p "$SCRATCH_DIR"
then
	echo "Unable to create scratch dir: $SCRATCH_DIR"
	usage
fi

if [ -d $OUT_DIR/spades ]
then
	echo "$OUT_DIR/spades already exists. Please remove it"
	exit 1
fi

SPADES_OUTPUT_ROOT=$SCRATCH_DIR/spades

# FASTQs are only read once - no need to stage to scratch if not already there
if ls $SCRATCH_DIR/Fastq/*.fastq.gz &> /dev/null
then
	FASTQ_DIR=$SCRATCH_DIR/Fastq
elif ls $OUT_DIR/Fastq/*.fastq.gz &> /dev/null
then
	FASTQ_DIR=$OUT_DIR/Fastq
else
	echo "No FASTQ files found"
	exit 1
fi

SAMPLES=$(ls $FASTQ_DIR/*.fastq.gz | cut -f1 -d_ | sort -u | grep -v Undetermined)
echo "Processing samples $SAMPLES"
for sample in $SAMPLES
do
	if ! $DIR/assemble_sample $SPADES_OUTPUT_ROOT/$sample $(find $FASTQ_DIR -name "$sample*fastq.gz" -print)
	then
		echo "Error assembling sample $sample"
		exit 1
	fi
done

if ! [ -z "$JOB_ID" ]
then
	# Running as an SGE_JOB
	if ! rsync -avpP $SPADES_OUTPUT_ROOT $OUT_DIR/spades
	then
		echo "Error syncing spades results to to output"
		exit 1
	fi
else
	echo "Running without local scratch"
	mv $SPADES_OUTPUT_ROOT $OUT_DIR/spades
	ln -s $OUT_DIR/spades $SPADES_OUTPUT_ROOT 
	ln -s $TARGET_RUN_DIR
fi

