#!/bin/bash

if ! [ -z "$JOB_ID" ]
then
	echo "This script cannot be used via qsub"
	exit 1
fi

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

. $DIR/scripts/parse_args.sh

echo $DIR/scripts/assemble_flowcell ${ALL_ARGS[@]} | \
	qsub -pe threaded 16 -l 'h_vmem=120G' -cwd -N assemble_flowcell -e $OUT_DIR/assemble_flowcell.err \
	-o $OUT_DIR/assemble_flowcell.out -m es -M $USER@illumina.com
