#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
. $DIR/scripts/parse_args.sh

if ! [ -d "$OUT_DIR" ] || ! mkdir -p "$OUT_DIR"
then
	echo "Unable to make output directory"
	usage
fi

if ! mkdir -p "$SCRATCH_DIR"
then
	echo "Unable to create scratch dir: $SCRATCH_DIR"
	usage
fi


$DIR/scripts/generate_fastq -r "$RUN_DIR" -o "$OUT_DIR" && \
	$DIR/scripts/assemble_samples -r "$RUN_DIR" -o "$OUT_DIR" 
	#&& \
	#$DIR/generate_metrics -r "$RUN_DIR" -o "$OUT_DIR" 
#rm -rf $SCRATCH_DIR
