#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
. $DIR/scripts/parse_args.sh
# arguments:
# standard ones
# fastq files

if [ -z "$OUT_DIR" ] || [ $# -lt 2 ]
then
	echo "Usage: $0 output_dir fastq files spades_args"
	exit 1
fi

if ! mkdir -p "$OUT_DIR"
then
	echo "unable to create $OUT_DIR"
	exit 1
fi

PATH=/illumina/thirdparty/spades/SPAdes-3.1.1-Linux/bin:$PATH
if [[ "$1" =~ .*_R1_.* ]]
then
	FQ_READ_1=$1
	FQ_READ_2=$2
else
	FQ_READ_2=$1
	FQ_READ_1=$2
fi

shift 2

if ! spades.py  $* -o "$OUT_DIR" --hqmp1-1 "$FQ_READ_1" --hqmp1-2 "$FQ_READ_2" --hqmp1-ff --careful
then
	echo "Assembly failed"
	exit 1
fi
