#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
. $DIR/scripts/parse_args.sh

if ! [ -d "$OUT_DIR" ] && ! mkdir -p "$OUT_DIR"
then
	echo "Unable to make output directory"
	usage
fi

if ! mkdir -p "$SCRATCH_DIR"
then
	echo "Unable to create scratch dir: $SCRATCH_DIR"
	usage
fi

FAILURES=false

if !  $DIR/scripts/align_samples -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT"
then
	echo "align_samples failed!"
	FAILURES=true
fi
if !  $DIR/scripts/downsample_fastqs -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT"
then
	echo "downsample_fastqs failed!"
	FAILURES=true
fi

if ! $DIR/scripts/assemble_samples -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT" 
then
	echo "assemble_samples failed!"
	FAILURES=true
fi
if ! $DIR/scripts/generate_all_metrics -r "$RUN_DIR" -o "$OUT_DIR" -s "$SCRATCH_ROOT" $OUT_DIR/spades
then
	echo "generate_all_metrics failed!"
	FAILURES=true
fi
rm -rf $SCRATCH_DIR

if $FAILURES
then
	echo "FAILURES OCCURRED! Look at the logs and figure out why"
	exit 1
fi
