#!/bin/bash
# arguments reference.fasta assembly.fasta output_name
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
. $DIR/scripts/tool_paths.sh
export PATH=$MUMMER_DIR:$PATH
TMPDIR=/tmp/plottmp.$$
mkdir -p $TMPDIR
pushd $TMPDIR
# replace annoying node names in assembly
sed 's/\(NODE_[0-9]*\)\(_.*\)/\1/g' $2 > assembly.fasta
nucmer -mumreference -c 1000 -l 100 -banded -d 10 ${1} assembly.fasta
delta-filter -1 out.delta > out.1delta
mummerplot -large -fat out.1delta --png
cp out.png $3
popd
rm -rf $TMPDIR
