#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
. $DIR/scripts/parse_args.sh
. $DIR/scripts/tool_paths.sh
# arguments
# standard ones
# assembly directory
# genome

if [ -z "$OUT_DIR" ] || [ $# -lt 2 ]
then
	echo "Usage: $0 -r run -o output spades_assembly genome_path"
	exit 1
fi

if ! mkdir -p "$OUT_DIR"
then
	echo "unable to create $OUT_DIR"
	exit 1
fi


ASSEMBLY=$1
GENOME=$2

# dot plots
$DIR/scripts/generate_plot "$GENOME" "$ASSEMBLY/scaffolds.fasta" "$OUT_DIR/dotplot.png"


if ! [ -f "$ASSEMBLY/scaffolds.fasta" ]
then
	echo "$ASSEMBLY does not contain a SPAdes assembly"
	exit 1
fi

if [[ ! -f "$GENOME" || ! $GENOME =~ .*\.fa ]]
then
	echo "$GENOME must be the full path to a .fa file"
	exit 1
fi


shift 2

export PATH=$BWA_DIR:$SAMTOOLS_DIR:$PATH
MYSCRATCH=$SCRATCH_DIR/bwa.$$
mkdir -p $MYSCRATCH
bwa bwasw -t 4  ${GENOME} $ASSEMBLY/scaffolds.fasta > $MYSCRATCH/scaffolds.sam
samtools view -bS $MYSCRATCH/scaffolds.sam > $MYSCRATCH/scaffolds.bam
samtools sort $MYSCRATCH/scaffolds.bam $OUT_DIR/scaffolds
samtools index $OUT_DIR/scaffolds.bam

# create a BED file showing coverage gaps
$BEDTOOLS_DIR/bedtools genomecov -ibam $OUT_DIR/scaffolds.bam -bga -split | grep -E ".*0$" > $OUT_DIR/gaps.bed

rm -rf $MYSCRATCH
