#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
. $DIR/scripts/parse_args.sh
. $DIR/scripts/tool_paths.sh
# arguments
# standard ones
# assembly directory
# genome

if [ -z "$OUT_DIR" ] || [ $# -lt 2 ]
then
	echo "Usage: $0 -r run -o output spades_assembly genome_path"
	exit 1
fi

if ! mkdir -p "$OUT_DIR"
then
	echo "unable to create $OUT_DIR"
	exit 1
fi


ASSEMBLY=$1
GENOME=$2

# dot plots
$DIR/scripts/generate_plot "$GENOME" "$ASSEMBLY/scaffolds.fasta" "$OUT_DIR/dotplot.png"


if ! [ -f "$ASSEMBLY/scaffolds.fasta" ]
then
	echo "$ASSEMBLY does not contain a SPAdes assembly"
	exit 1
fi

if [[ ! -f "$GENOME" || ! $GENOME =~ .*\.fa ]]
then
	echo "$GENOME must be the full path to a .fa file"
	exit 1
fi


shift 2

export PATH=$LAST_DIR:$PATH
export PATH=$PYTHON_DIR:$PATH
NEWGENOME=$SCRATCH_DIR/genome.$$
MYSCRATCH=$SCRATCH_DIR/last.$$
mkdir -p $MYSCRATCH
mkdir -p $NEWGENOME
lastdb -c $NEWGENOME/genome_db $GENOME
lastal -Q0 $NEWGENOME/genome_db $ASSEMBLY/scaffolds.fasta | last-map-probs.py > $MYSCRATCH/align.maf
maf-sort.sh $MYSCRATCH/align.maf > $MYSCRATCH/align_sorted.maf
maf-convert.py sam $MYSCRATCH/align_sorted.maf > $MYSCRATCH/align_sorted.sam
$SAMTOOLS_DIR/samtools view -t ${GENOME}.fai -F 0x800 -q 1 -S $MYSCRATCH/align_sorted.sam > $MYSCRATCH/align_sorted_filtered.sam
$SAMTOOLS_DIR/samtools view -t ${GENOME}.fai -Sb $MYSCRATCH/align_sorted_filtered.sam > $MYSCRATCH/align_sorted_filtered.bam
$SAMTOOLS_DIR/samtools sort $MYSCRATCH/align_sorted_filtered.bam $OUT_DIR/scaffolds
$SAMTOOLS_DIR/samtools index $OUT_DIR/scaffolds.bam

# create a BED file showing coverage gaps
$BEDTOOLS_DIR/bedtools genomecov -ibam $OUT_DIR/scaffolds.bam -bga -split | grep -E ".*0$" > $OUT_DIR/gaps.bed

rm -rf $MYSCRATCH
rm -rf $NEWGENOME
