#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
. $DIR/scripts/parse_args.sh
. $DIR/scripts/samplesheet.sh

# arguments:
# normal ones
# spades output dir

if ! [ -d "$OUT_DIR" ] && ! mkdir -p "$OUT_DIR"
then
	echo "Unable to make output directory"
	usage
fi

if ! mkdir -p "$SCRATCH_DIR"
then
	echo "Unable to create scratch dir: $SCRATCH_DIR"
	usage
fi

if [ -d $OUT_DIR/quast ]
then
	echo "$OUT_DIR/quast already exists. Please remove it"
	exit 1
fi
if ! mkdir -p $OUT_DIR/quast
then
	echo "Unable to create $OUT_DIR/quast"
	exit 1
fi
SPADES_OUTPUT_ROOT=$1
failed=false

SAMPLES=$(cd $SPADES_OUTPUT_ROOT && ls)
for sample in $SAMPLES
do
	echo "Processing sample $sample"
	GENOME=$(get_sample_genome $RUN_DIR/SampleSheet.csv $sample)
	echo "Sample: $sample, genome: $GENOME"
	if ! $DIR/scripts/generate_metrics -r "$RUN_DIR" -o "$OUT_DIR/quast/$sample" $SPADES_OUTPUT_ROOT/$sample $GENOME
	then
		echo "Error generating metrics for $sample"
		failed=true
	fi
	if ! $DIR/scripts/generate_picard_metrics -r "$RUN_DIR" -o "$OUT_DIR/picard/$sample" $OUT_DIR/Alignment/$sample*bam $GENOME
	then
		echo "Error generating picard metrics for $sample"
		failed=true
	fi
	if ! $DIR/scripts/generate_visualizations -r "$RUN_DIR" -o "$OUT_DIR/visualization/$sample" $SPADES_OUTPUT_ROOT/$sample $GENOME
	then
		echo "Error generating visualizations for $sample"
		failed=true
	fi
done


if [ -f $OUT_DIR/../summary_stats.js ]
then
	$DIR/scripts/generate_analysis_stats -r "$RUN_DIR" -o "$OUT_DIR"  >> $OUT_DIR/../summary_stats.js
fi

if $failed
then
	exit 1
fi
