#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
. $DIR/scripts/parse_args.sh
. $DIR/scripts/tool_paths.sh
# arguments
# standard ones
# assembly directory
# genome

if [ -z "$OUT_DIR" ] || [ $# -lt 2 ]
then
	echo "Usage: $0 -r run -o output spades_assembly genome_path"
	exit 1
fi

if ! mkdir -p "$OUT_DIR"
then
	echo "unable to create $OUT_DIR"
	exit 1
fi


ASSEMBLY=$1
GENOME=$2

if ! [ -f "$ASSEMBLY/scaffolds.fasta" ]
then
	echo "$ASSEMBLY does not contain a SPAdes assembly"
	exit 1
fi

if [[ ! -f "$GENOME" || ! $GENOME =~ .*\.fa ]]
then
	echo "$GENOME must be the full path to a .fa file"
	exit 1
fi


shift 2
export PATH=$QUAST_DIR:$PYTHON_DIR:$PATH

failed=false

if ! quast.py --debug --scaffolds -o "$OUT_DIR" -R "$GENOME" "$ASSEMBLY/scaffolds.fasta"
then
	echo "Quast failed"
	failed=true
fi


if $failed
then
	exit 1
fi
