#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
. $DIR/scripts/parse_args.sh
. $DIR/scripts/samplesheet.sh

# arguments:

SAMPLES=$(cd $OUT_DIR/spades && ls)
for sample in $SAMPLES
do
	GENOME=$(dirname $(get_sample_genome $RUN_DIR/SampleSheet.csv $sample))
	shopt -s nocasematch;
	if [[ $sample =~ ^ec ]]
	then
		if ! $DIR/scripts/generate_per_genome_report $GENOME "SAMPLE_ID=ec" $OUT_DIR/.. > $OUT_DIR/../EC.report.html
		then
			echo "Error generating summary report for EC"
			failed=true
		fi
	elif [[ $sample =~ ^bc ]]
	then
		if ! $DIR/scripts/generate_per_genome_report $GENOME "SAMPLE_ID=bc" $OUT_DIR/.. > $OUT_DIR/../BC.report.html
		then
			echo "Error generating summary report for BC"
			failed=true
		fi
	elif [[ $sample =~ ^rs ]]
	then
		if ! $DIR/scripts/generate_per_genome_report $GENOME "SAMPLE_ID=rs" $OUT_DIR/.. > $OUT_DIR/../RS.report.html
		then
			echo "Error generating summary report for RS"
			failed=true
		fi
	elif [[ $sample =~ ^sc ]]
	then
		if ! $DIR/scripts/generate_per_genome_report $GENOME "SAMPLE_ID=sc" $OUT_DIR/.. > $OUT_DIR/../SC.report.html
		then
			echo "Error generating summary report for SC"
			failed=true
		fi
	elif [[ $sample =~ ^mt ]]
	then
		if ! $DIR/scripts/generate_per_genome_report $GENOME "SAMPLE_ID=mt" $OUT_DIR/.. > $OUT_DIR/../MT.report.html
		then
			echo "Error generating summary report for MT"
			failed=true
		fi
	elif [[ $sample =~ ^bper ]]
	then
		if ! $DIR/scripts/generate_per_genome_report $GENOME "SAMPLE_ID=bper" $OUT_DIR/.. > $OUT_DIR/../BP.report.html
		then
			echo "Error generating summary report for BP"
			failed=true
		fi
	elif [[ $sample =~ ^bp ]]
	then
		if ! $DIR/scripts/generate_per_genome_report $GENOME "SAMPLE_ID=bp[^e]" $OUT_DIR/.. > $OUT_DIR/../BP.report.html
		then
			echo "Error generating summary report for BP"
			failed=true
		fi
	elif [[ $sample =~ ^lm ]]
	then
		if ! $DIR/scripts/generate_per_genome_report $GENOME "SAMPLE_ID=lm" $OUT_DIR/.. > $OUT_DIR/../LM.report.html
		then
			echo "Error generating summary report for LM"
			failed=true
		fi
	fi
done

cp $DIR/scripts/*.js $OUT_DIR/..


